show databases;
use sqlpractice;

show tables;


CREATE TABLE IF NOT EXISTS Products(
    PRODUCT_ID INT,
    PRODUCT_NAME VARCHAR(30),
    CATEGORY VARCHAR(30),
    PRICE INT,
    STOCK INT,
    BRAND VARCHAR(30)
);

SHOW TABLES;


INSERT INTO  products VALUES
(1,"LAPTOP",'ELECTRONICS',55000,10,"DELL"),
(2,"MOUSE",'ELECTRONICS',700,50,"LOGITECH"),
(3,"KEYBORD",'ELECTRONICS',1500,35,"HP"),
(4,"CHAIR",'FURNITURE',4500,15,"GREENSOUL"),
(5,"TABLE",'FURNITURE',8000,8,"IKEA"),
(6,"NOTEBOOK",'STATIONARY',80,100,"CLASSMATE"),
(7,"PEN",'STATIONARY',20,200,"CELLO"),
(8,"BOTTLE",'KITCHEN',500,40,"MILTON"),
(9,"BAG",'ACCESSORIES',1200,25,"SKYBAGS"),
(10,"SHOES",'FASHION',2500,18,"PUMA");


SELECT * FROM products;

SELECT PRODUCT_NAME,PRICE FROM products;

SELECT PRODUCT_NAME,CATEGORY,BRAND FROM products;

SELECT PRODUCT_NAME AS ITEAM_NAME , PRICE AS ITEM_PRICE FROM products;


SELECT DISTINCT BRAND FROM products;


SELECT DISTINCT CATEGORY FROM products;


SELECT PRODUCT_NAME FROM products WHERE CATEGORY='ELECTRONICS';


SELECT PRODUCT_NAME FROM products WHERE PRICE>1000;

SELECT PRODUCT_NAME FROM products WHERE PRICE <1000;

SELECT PRODUCT_NAME ,STOCK FROM products WHERE STOCK >=40;

SELECT PRODUCT_NAME,PRICE FROM products WHERE PRICE<=500;


SELECT PRODUCT_NAME ,CATEGORY FROM products WHERE CATEGORY!='FURNITURE';


SELECT PRODUCT_NAME , CATEGORY FROM products WHERE CATEGORY IN ("FURNITURE","STATIONARY");


SELECT PRODUCT_NAME , PRICE FROM products WHERE CATEGORY='FURNITURE' AND PRICE<=1000;



SELECT PRODUCT_NAME , PRICE FROM products WHERE PRICE  BETWEEN 500 AND 5000;


SELECT PRODUCT_NAME,CATEGORY FROM products WHERE CATEGORY IN ("ELECTRONICS","FURNITURE","FASHION");


SELECT PRODUCT_NAME,BRAND FROM products WHERE BRAND NOT IN ("DELL","HP","PUMA");