SELECT MAX(SAL) FROM EMP

SELECT SAL FROM EMP

SELECT MAX(HIREDATE) AS MAXDATE FROM EMP

SELECT MAX(ENAME) AS ORDNAME FROM EMP


SELECT MIN(SAL) FROM EMP
SELECT MIN(HIREDATE) FROM EMP

SELECT MIN(ENAME) FROM EMP

SELECT  ROUND(SUM(SAL),2) FROM EMP


SELECT FORMAT(ROUND(SUM(SAL),-2),'C','EN-IN') FROM EMP

SELECT SUM(SAL)/12 AS EQUALSAL  FROM EMP 

SELECT COUNT(COMM) FROM EMP

SELECT COUNT(DISTINCT(SAL)) FROM EMP



SELECT COUNT(*)  FROM EMP WHERE  HIREDATE BETWEEN  '1981-01-01' AND '1981-12-31'

SELECT COUNT(*) FROM EMP WHERE DATEPART(YY,HIREDATE) = 1981

SELECT COUNT(*) FROM EMP WHERE DATEPART(DD,HIREDATE) = 1

SELECT COUNT(*) FROM EMP WHERE DATEPART(DW,HIREDATE) IN (1,7)




