select REPLACE ('Hello','ELL','ABC')

select REPLACE ('Hello','L','ABC')

select REPLACE ('Hello','ELO','ABC') 

select REPLACE ('@@HE@@LL@@O','@','')

SET IMPLICIT_TRANSACTIONS ON 

SELECT REPLACE (HIREDATE,'-04-','-10-') FROM EMP

SELECT * FROM EMP

ROLLBACK


UPDATE EMP  SET  HIREDATE = REPLACE (HIREDATE,'--09','--10')
--FROM EMP

SELECT TRANSLATE('HELLO','ELO','ABC')

SELECT ENAME,TRANSLATE(SAL,'0123456789.','$BT*#&@^%!K') AS ENSAL FROM EMP


--UPDATE EMP SET SAL = TRANSLATE(SAL,'0123456789.','$BT*#&@^%!K')
SELECT REPLACE(TRANSLATE ('!@HE#$LL%^O&*','!@#$%^&*','@@@@@@@@'),'@','')

SELECT REPLACE(TRANSLATE('ABC123XYZ56','123456','******'),'*','')
SELECT REPLACE(TRANSLATE('ABC123XYZ56','ABCXYZ','******'),'*','')

SELECT DATEPART(YY,GETDATE())
SELECT DATEPART(HH,GETDATE())
SELECT DATEPART(DD,GETDATE())
SELECT DATEPART(QQ,GETDATE())
SELECT DATEPART(SS,GETDATE())
SELECT DATEPART(MI,GETDATE())

SELECT ENAME , DATEPART(YY,HIREDATE) AS YEAROFJOIN FROM EMP

SELECT ENAME , DATEPART(YY,HIREDATE) AS YEAROFJOIN FROM EMP
WHERE DATEPART(YY,HIREDATE) IN ('1983','1985','1983')


SELECT ENAME , DATEPART(YY,HIREDATE) AS YEAROFJOIN FROM EMP
WHERE DATEPART(YY,HIREDATE)%4=0 

SELECT ENAME , DATEPART(YY,HIREDATE) AS YEAROFJOIN FROM EMP
WHERE DATEPART(DW,HIREDATE)=1 

SELECT * FROM EMP
WHERE DATEPART(QQ,HIREDATE)=2 AND DATEPART(YY,HIREDATE)=1981

SELECT ENAME, HIREDATE,DATENAME(DW,HIREDATE) AS DAYY FROM EMP
SELECT DATENAME(DW,'1947-08-15') AS INDDAY

SELECT DATEADD(DD,10,GETDATE())





