SELECT * FROM EMPLOYEES;

SELECT NAME,SALARY FROM EMPLOYEES;



SELECT NAME,SALARY,CITY FROM EMPLOYEES;


SELECT NAME,DEPARTMENT,CITY FROM EMPLOYEES;



SELECT NAME AS EMP_NAME , SALARY AS MONTLY_SALARY FROM EMPLOYEES;

SELECT DISTINCT DEPARTMENT FROM EMPLOYEES;


SELECT DISTINCT CITY FROM EMPLOYEES;